import { normalizeTag, releaseAssetName } from "./assets.ts";
import type { CompileTarget } from "../buildBinary.ts";

const REPO = "jrpat/jif";

// The four platforms brew serves: macOS and Linux, arm64 and x64.
const BREW_TARGETS = {
  darwinArm: "bun-darwin-arm64",
  darwinIntel: "bun-darwin-x64",
  linuxArm: "bun-linux-arm64",
  linuxIntel: "bun-linux-x64",
} as const satisfies Record<string, CompileTarget>;

export function parseChecksums(text: string): Map<string, string> {
  const sums = new Map<string, string>();
  for (const line of text.split("\n")) {
    const match = /^([0-9a-f]{64})\s+(\S+)$/.exec(line.trim());
    if (match) {
      sums.set(match[2]!, match[1]!);
    }
  }
  return sums;
}

export function renderFormula(options: {
  tag: string;
  checksums: ReadonlyMap<string, string>;
}): string {
  const { tag, version, prerelease } = normalizeTag(options.tag);
  if (prerelease) {
    throw new Error(`Refusing to render a formula for prerelease ${tag}`);
  }

  const asset = (target: CompileTarget) => {
    const name = releaseAssetName(target, tag);
    const sha256 = options.checksums.get(name);
    if (!sha256) {
      throw new Error(`No checksum for ${name} in SHA256SUMS`);
    }
    return {
      url: `https://github.com/${REPO}/releases/download/${tag}/${name}`,
      sha256,
    };
  };

  const darwinArm = asset(BREW_TARGETS.darwinArm);
  const darwinIntel = asset(BREW_TARGETS.darwinIntel);
  const linuxArm = asset(BREW_TARGETS.linuxArm);
  const linuxIntel = asset(BREW_TARGETS.linuxIntel);

  return `# Generated by scripts/release/updateTap.ts in ${REPO} — do not edit by hand.
class Jif < Formula
  desc "Keyboard-first terminal UI for Jujutsu"
  homepage "https://github.com/${REPO}"
  license "MIT"
  version "${version}"

  depends_on "jj"

  on_macos do
    on_arm do
      url "${darwinArm.url}"
      sha256 "${darwinArm.sha256}"
    end
    on_intel do
      url "${darwinIntel.url}"
      sha256 "${darwinIntel.sha256}"
    end
  end

  on_linux do
    on_arm do
      url "${linuxArm.url}"
      sha256 "${linuxArm.sha256}"
    end
    on_intel do
      url "${linuxIntel.url}"
      sha256 "${linuxIntel.sha256}"
    end
  end

  def install
    bin.install "jif"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/jif --version")
  end
end
`;
}
